### ISSUE TITLE
Question about the script

### ISSUE THREAD

**Issue by CoreKillaJS** [cadburry6969/qb-weaponsonback#1]
Once i login with a weapon in my inventory it wont show into i restart the script.

**Comment by Terranzin** [comment]
I have same issue.

**Comment by LwkyLion** [comment]
Have you guys figured out what causes this?

**Comment by Brotatochips11** [comment]
Any fix for this?

**Comment by Brotatochips11** [comment]
> Have you guys figured out what causes this?

Any fix for this?

**Comment by cadburry6969** [comment]
Do these changes and try
https://github.com/cadburry6969/qb-weaponsonback/commit/ff4ad237fcc352da4f66d5d2b7f1567c3bd00a13

**Comment by Brotatochips11** [comment]
> Do these changes and try [ff4ad23](https://github.com/cadburry6969/qb-weaponsonback/commit/ff4ad237fcc352da4f66d5d2b7f1567c3bd00a13)

It worked flawlessly!
