### ISSUE TITLE
Weapons do not disappear

### ISSUE THREAD

**Issue by Im-Kayun** [cadburry6969/qb-weaponsonback#2]
After I remove the weapons from the inventory, they are still on my back.
![image](https://user-images.githubusercontent.com/84230221/171490614-b1296e7b-de9d-460e-83d7-d5cbfa1e6d44.png)

**Comment by kingofkingzcd** [comment]
same problem

**Comment by kingofkingzcd** [comment]
![image](https://user-images.githubusercontent.com/83891867/173127738-bbdf5b23-77d5-4172-a1c1-22956e647c02.png)
also gives this error so id assume this is the problem

**Comment by YellowxBeam** [comment]
> 

I have the same error bro, idk how to fix it..
