### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by AndreasFromDanmark** [cadburry6969/qb-weaponsonback#4]
I dont know 🤔 

![image](https://user-images.githubusercontent.com/35656492/171742277-6d6d8770-f8dc-43fc-a726-62fb7116a23f.png)

![image](https://user-images.githubusercontent.com/35656492/171742303-61105aa1-748b-4ced-a9e3-6ef1d1200188.png)

**Comment by cadburry6969** [comment]
https://github.com/cadburry6969/qb-weaponsonback/commit/f056719deb053632677518ffe4a0b7397fd22a14
